version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - GROQ_API_KEY=${GROQ_API_KEY}
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
  ollama_data:
